config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/users/:id', :to => 'users#show', :as => :user

  resources :adverts
  root "adverts#index"
end

app/models/advert.rb
class Advert < ApplicationRecord
  def self.search(search)
    where("title LIKE ? OR description LIKE ? OR price LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

  belongs_to :user
  belongs_to :category

  validates :title, :description, presence: true,
            length: { minimum: 5 }


  has_attached_file :image, styles: { medium: "700x300>", thumb: "100x100>" }, default_url:lambda {|image| ActionController::Base.helpers.asset_path("assets/default.jpg")}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :adverts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :adverts
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  def index
    if params[:search]
      @adverts = Advert.search(params[:search]).paginate(:page => params[:page], :per_page => 3)
    else
      @adverts = Advert.paginate(:page => params[:page], :per_page => 3)
    end
  end

  def new
    if current_user
      @advert = Advert.new
    else
      redirect_to root_path
    end
  end

  def edit
    @advert = Advert.find(params[:id])

    if current_user
      unless current_user.id == @advert.user_id
        redirect_to advert_path , alert: "Vous n'êtes pas propriétaire de cette annonce"
      end
    else
      redirect_to advert_path , alert: "Vous devez être connecté et être propriètaire de cette annonce pour la modifier"
    end
  end

  def update
    @advert = Advert.find(params[:id])

    if @advert.update(advert_params)
      redirect_to @advert
    else
      render 'edit'
    end
  end

  def create
    if current_user.present?
      @advert = current_user.adverts.build(advert_params)
      if @advert.save
        redirect_to root_url
      else
        render :new
      end
    else
      redirect_to root_path , alert: "Vous devez être connecté pour publier une anonce"
    end
  end

  def show
    @advert = Advert.find(params[:id])
  end

  def destroy
    @advert = Advert.find(params[:id])
    @advert.destroy

    redirect_to adverts_path
  end

  private
  def advert_params
    params.require(:advert).permit(:title, :description, :price, :image, :category_id, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    if current_user.id == @user.id
      @adverts = @user.adverts.paginate(:page => params[:page], :per_page => 3)
    else
      redirect_to root_path
    end
  end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/adverts/_form.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-md-6">

      <%= form_for @advert, html: { multipart: true } do |f| %>

          <% if @advert.errors.any? %>
              <div id="error_explanation">
                <h2>
                  <%= pluralize(@advert.errors.count, "error") %> prohibited
                  this advert from being saved:
                </h2>
                <ul>
                  <% @advert.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="form-group">
            <%= f.file_field :image, :class => 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :titre %><br>
            <%= f.text_field :title, :class => 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :description %><br>
            <%= f.text_area :description, :class => 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :prix %><br>
            <%= f.text_field :price, :class => 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :categorie %><br>
            <%= f.collection_select :category_id, Category.all, :id, :title, {}, { :class => 'form-control' } %>
          </div>

          <div class="form-group">
            <%= f.submit 'Ajouter', :class => 'btn btn-primary'  %>
          </div>

      <% end %>
    </div>
  </div>
</div>

app/views/adverts/edit.html.erb
<h1>Editing advert</h1>

<%= render 'form' %>

<%= link_to 'Retour', adverts_path, class:"btn btn-default" %>

app/views/adverts/index.html.erb
<% if @adverts.present? %>
    <h1>Liste des annonces</h1>
    <%- if current_user %>
        <%= link_to 'Ajouter une annonce', new_advert_path , class:"btn btn-success" %>
    <% else %>
        <div class="alert alert-info" role="alert">Vous devez être connecté pour ajouter une annonce</div>
    <% end %>
    <%= will_paginate @adverts %>
    <hr>
        <% @adverts.each do |advert| %>
        <div class="row">
          <div class="col-md-6">
              <%= image_tag advert.image.url(:medium) , class: "img-responsive" %>
          </div>
          <div class="col-md-6">
            <h3><%= advert.title %></h3>
            <p><%= advert.description %></p>
            <h4><%= advert.price %> &euro; </h4>
            <h5>Catégorie : <span class="label label-info"><%= advert.category.title %></span></h5>
            <%= link_to 'Voir', advert_path(advert), class: "btn btn-primary" %>
            <%- if current_user %>
                <%- if current_user.id == advert.user_id %>
                    <%= link_to 'Modifier', edit_advert_path(advert), class: "btn btn-warning"  %>
                    <%= link_to 'Supprimer', advert_path(advert), class: "btn btn-danger" ,
                                    method: :delete,
                                    data: { confirm: 'Etes-vous sur ?' } %>
                <% end %>
            <% end %>
          </div>
        </div>
        <hr>
        <% end %>
<% else %>
    <h1>Aucune annonce disponible</h1>
    <%- if current_user %>
        <%= link_to 'Ajouter une annonce', new_advert_path , class:"btn btn-success" %>
    <% else %>
        <div class="alert alert-info" role="alert">Vous devez être connecté pour ajouter une annonce</div>
    <% end %>
<% end %>

app/views/adverts/new.html.erb
<h1>Nouvelle annonce</h1>

<%= render 'form' %>

<%= link_to 'Retour', adverts_path, class:"btn btn-default" %>

app/views/adverts/show.html.erb
<div class="row">
  <div class="col-md-6">
    <a href="#">
      <div class="col-md-6">
        <%= image_tag @advert.image.url(:medium) , class: "img-responsive" %>
      </div>
    </a>
  </div>
  <div class="col-md-6">
    <h3><%= @advert.title %></h3>
    <p><%= @advert.description %></p>
    <h4><%= @advert.price %> &euro;</h4>
    <h5>Catégorie : <span class="label label-info"><%= @advert.category.title %></span></h5>
    <%= link_to 'Retour', adverts_path, class: "btn btn-default" %>
    <%- if current_user %>
        <%- if current_user.id == @advert.user_id %>
            <%= link_to 'Modifier', edit_advert_path(@advert), class: "btn btn-warning"  %>
            <%= link_to 'Supprimer', advert_path(@advert), class: "btn btn-danger" ,
                        method: :delete,
                        data: { confirm: 'Etes-vous sur ?' } %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeboncoinApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!-- Navigation -->
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%- if current_user %>
            <div class="navbar-brand">Bienvenue, <%= current_user.email %></div>
        <% else %>
            <%= link_to "Se connecter", new_user_session_path , { :class=>"navbar-brand" } %>
        <% end %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <%= form_tag(adverts_path, :method => "get", id: "search-form", class:"navbar-form navbar-left") do %>
            <div class="form-group">
              <%= text_field_tag :search, params[:search], placeholder: "Recherche" , class: "form-control" %>
            </div>
            <%= submit_tag "OK", class:"btn btn-default" %>
        <% end %>
        <ul class="nav navbar-nav">
          <%- if current_user %>
              <li> <%= link_to "Mes annonces", current_user %></li>
              <li> <%= link_to "Se déconnecter", destroy_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/show.html.erb
<% if @adverts.present? %>
    <h1>Liste de mes annonces - <%= @user.email %></h1>
    <%- if current_user %>
        <%= link_to 'Ajouter une annonce', new_advert_path , class:"btn btn-success" %>
    <% end %>
    <%= will_paginate @adverts %>
    <hr>
    <% @adverts.each do |advert| %>
        <div class="row">
          <div class="col-md-6">
            <a href="#">
              <div class="col-md-6">
                <%= image_tag advert.image.url(:medium) , class: "img-responsive" %>
              </div>
            </a>
          </div>
          <div class="col-md-6">
            <h3><%= advert.title %></h3>
            <p><%= advert.description %></p>
            <h4><%= advert.price %> &euro;</h4>
            <%= link_to 'Voir', advert_path(advert), class: "btn btn-primary" %>
            <%- if current_user %>
                <%- if current_user.id == advert.user_id %>
                    <%= link_to 'Modifier', edit_advert_path(advert), class: "btn btn-warning"  %>
                    <%= link_to 'Supprimer', advert_path(advert), class: "btn btn-danger" ,
                                method: :delete,
                                data: { confirm: 'Etes-vous sur ?' } %>
                <% end %>
            <% end %>
          </div>
        </div>
        <hr>
    <% end %>

<% else %>
    <h1>Vous n'avez pas d'annonce en cours </h1>
    <%- if current_user %>
        <%= link_to 'Ajouter une annonce', new_advert_path , class:"btn btn-success" %>
    <% end %>
<% end %>